import { z } from 'zod';
import { MAX_DISCOUNT_PERCENT, MAX_PRICE_TOMAN, MIN_DISCOUNT_PERCENT } from './money.js';

// ---------- primitives ----------

export const ObjectIdSchema = z.string().regex(/^[a-f0-9]{24}$/, 'شناسه نامعتبر است.');

/** Stored media file name (random, generated by the server). Never a path. */
export const MediaNameSchema = z.string().regex(/^[a-z0-9][a-z0-9-]{0,80}\.(webp|png|jpg|svg)$/);

const text = (max: number, min = 1) => z.string().trim().min(min).max(max);

export const ROLES = ['stall_admin', 'super_admin'] as const;
export const RoleSchema = z.enum(ROLES);
export type Role = z.infer<typeof RoleSchema>;

export const USERNAME_PATTERN = /^[a-z0-9][a-z0-9._-]{2,31}$/;
export const UsernameSchema = z
  .string()
  .trim()
  .toLowerCase()
  .regex(USERNAME_PATTERN, 'نام کاربری ۳ تا ۳۲ حرف انگلیسی کوچک، عدد، نقطه، خط تیره یا زیرخط است.');

/** Password policy for new passwords: at least 8 characters, at least one letter and one digit. */
export const NewPasswordSchema = z
  .string()
  .min(8, 'رمز باید حداقل ۸ حرف باشد.')
  .max(128, 'رمز طولانی است.')
  .refine((v) => /\p{L}/u.test(v) && /\p{Nd}/u.test(v), 'رمز باید حرف و عدد داشته باشد.');

export const CATEGORY_ICON_KEYS = [
  'pizza',
  'burger',
  'kebab',
  'fried-chicken',
  'steak',
  'sushi',
  'sandwich',
  'dessert',
] as const;
export const CategoryIconSchema = z.enum(CATEGORY_ICON_KEYS);

export const FOOD_TINTS = ['food-tint-1', 'food-tint-2', 'food-tint-3', 'food-tint-4'] as const;
export const FoodTintSchema = z.enum(FOOD_TINTS);

export const PriceSchema = z.number().int().min(0).max(MAX_PRICE_TOMAN);

/** Tehran local calendar date, ISO formatted (YYYY-MM-DD, Gregorian). The UI converts to/from Jalali. */
export const LocalDateSchema = z.iso.date();
const Instant = z.iso.datetime({ offset: true });

// ---------- schedule ----------

/** "HH:MM" 00:00–23:59. */
export const TimeSchema = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'ساعت نامعتبر است.');
/** Closing time additionally allows "24:00" meaning midnight at the end of the day. */
export const ClosingTimeSchema = z.union([TimeSchema, z.literal('24:00')]);

/**
 * One opening interval per weekday. close < open means the interval runs past midnight
 * into the next day (overnight). open === close is rejected as ambiguous.
 */
export const DayScheduleSchema = z
  .strictObject({ closed: z.boolean(), open: TimeSchema, close: ClosingTimeSchema })
  .refine((d) => d.closed || d.open !== d.close, { message: 'ساعت شروع و پایان یکی است.', path: ['close'] });

/** Exactly seven days; index 0 = Saturday (شنبه) … index 6 = Friday (جمعه), Asia/Tehran local time. */
export const WeeklyScheduleSchema = z.array(DayScheduleSchema).length(7);
export type WeeklySchedule = z.infer<typeof WeeklyScheduleSchema>;

export const DEFAULT_WEEKLY_HOURS: WeeklySchedule = Array.from({ length: 7 }, () => ({
  closed: false,
  open: '12:00',
  close: '23:00',
}));

/** Manual open/closed override; `until` = next scheduled opening start, null when none exists. */
export const ManualOverrideSchema = z.strictObject({
  state: z.enum(['open', 'closed']),
  until: Instant.nullable(),
});

// ---------- write inputs ----------

export const FoodcourtInputSchema = z.strictObject({
  name: text(60),
  logo: MediaNameSchema.nullable(),
  menuOpen: z.boolean(),
  closedMessage: text(200, 0),
});

/** Super admin: create a stall together with its stall-admin account. */
export const StallCreateInputSchema = z.strictObject({
  name: text(40),
  logo: MediaNameSchema.nullable(),
  visible: z.boolean(),
  adminUsername: UsernameSchema,
});

/** Super admin: stall identity and menu visibility. */
export const StallUpdateInputSchema = z.strictObject({
  name: text(40),
  logo: MediaNameSchema.nullable(),
  visible: z.boolean(),
});

/** Stall panel: short intro and weekly hours. */
export const StallProfileInputSchema = z.strictObject({
  intro: text(40, 0),
  weeklyHours: WeeklyScheduleSchema,
});

/** Stall panel "open now" switch. */
export const ManualStatusInputSchema = z.strictObject({ isOpen: z.boolean() });

export const AccountUsernameInputSchema = z.strictObject({ username: UsernameSchema });

export const GlobalCategoryInputSchema = z.strictObject({
  name: text(30),
  icon: CategoryIconSchema,
});

export const StallCategoryInputSchema = z.strictObject({ name: text(40) });

/** Full new order; must contain exactly the existing ids. */
export const ReorderInputSchema = z.strictObject({
  ids: z.array(ObjectIdSchema).max(500).refine((ids) => new Set(ids).size === ids.length, 'شناسه‌ی تکراری.'),
});

export const DiscountSchema = z
  .strictObject({
    percent: z.number().int().min(MIN_DISCOUNT_PERCENT).max(MAX_DISCOUNT_PERCENT),
    startDate: LocalDateSchema,
    endDate: LocalDateSchema,
  })
  .refine((d) => d.startDate <= d.endDate, { message: 'تاریخ پایان باید بعد از تاریخ شروع باشد.', path: ['endDate'] });

export const FoodInputSchema = z.strictObject({
  name: text(60),
  description: text(120, 0),
  price: PriceSchema,
  image: MediaNameSchema.nullable(),
  tint: FoodTintSchema,
  categoryId: ObjectIdSchema,
  stallCategoryId: ObjectIdSchema,
  available: z.boolean(),
  discount: DiscountSchema.nullable(),
});

export const AvailabilityInputSchema = z.strictObject({ available: z.boolean() });

/** Anonymous popularity event: one successful "+" (add or quantity increment) for a food. */
export const PopularityEventSchema = z.strictObject({ foodId: ObjectIdSchema });

const flag = z.enum(['true', 'false']).transform((v) => v === 'true');

const tomanParam = z
  .string()
  .regex(/^\d{1,10}$/)
  .transform(Number);

/** Customer search/filter query string (FilterSheet + StallFilterChip + category page). */
export const SearchQuerySchema = z
  .strictObject({
  q: z.string().max(100).optional(),
  stallId: ObjectIdSchema.optional(),
  categoryId: ObjectIdSchema.optional(),
  onlyOpen: flag.optional(),
  onlyDiscounted: flag.optional(),
  /** Inclusive bounds on the price the customer pays today. */
  minPrice: tomanParam.optional(),
  maxPrice: tomanParam.optional(),
  sort: z.enum(['default', 'cheapest', 'priciest', 'popular']).optional(),
  })
  .refine((q) => q.minPrice === undefined || q.maxPrice === undefined || q.minPrice <= q.maxPrice, {
    message: 'بازه‌ی قیمت نامعتبر است.',
    path: ['maxPrice'],
  });

// ---------- auth ----------

export const LoginInputSchema = z.strictObject({
  username: z.string().trim().toLowerCase().min(1).max(64),
  password: z.string().min(1).max(128),
});

export const ChangePasswordInputSchema = z
  .strictObject({
    currentPassword: z.string().min(1).max(128),
    newPassword: NewPasswordSchema,
    confirmPassword: z.string(),
  })
  .refine((v) => v.newPassword === v.confirmPassword, { message: 'تکرار رمز یکی نیست.', path: ['confirmPassword'] });

// ---------- responses ----------

export const AccountResponseSchema = z.strictObject({
  id: ObjectIdSchema,
  username: z.string(),
  role: RoleSchema,
  stallId: ObjectIdSchema.nullable(),
});
export type AccountResponse = z.infer<typeof AccountResponseSchema>;

export const SessionResponseSchema = z.strictObject({
  account: AccountResponseSchema,
  csrfToken: z.string(),
});
export type SessionResponse = z.infer<typeof SessionResponseSchema>;

/** Returned once by stall creation and password reset; never retrievable again. */
export const TemporaryPasswordResponseSchema = z.strictObject({
  username: z.string(),
  temporaryPassword: z.string(),
});

export const MediaUploadResponseSchema = z.strictObject({ name: MediaNameSchema, url: z.string() });

const url = z.string(); // relative media URL such as /api/media/<name>

export const PublicFoodcourtSchema = z.strictObject({
  name: z.string(),
  logoUrl: url.nullable(),
  menuOpen: z.boolean(),
  closedMessage: z.string(),
});

export const PublicStallSchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  intro: z.string(),
  logoUrl: url.nullable(),
  isOpen: z.boolean(),
  /** Start of the next opening, when closed and one exists. */
  opensAt: Instant.nullable(),
  sortOrder: z.number().int(),
  foodCount: z.number().int(),
});

export const PublicCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  icon: CategoryIconSchema,
  sortOrder: z.number().int(),
  /** Foods of visible stalls in this category (sold-out included). */
  foodCount: z.number().int(),
});

export const PublicStallCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  name: z.string(),
  sortOrder: z.number().int(),
});

export const PublicFoodSchema = z.strictObject({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  categoryId: ObjectIdSchema,
  stallCategoryId: ObjectIdSchema,
  name: z.string(),
  description: z.string(),
  price: PriceSchema,
  /** Equals price unless a discount is active today (Tehran). */
  finalPrice: PriceSchema,
  discountPercent: z.number().int().nullable(),
  imageUrl: url.nullable(),
  tint: FoodTintSchema,
  available: z.boolean(),
});

/**
 * Whole customer menu in one response (also the offline cache unit). When the menu is closed
 * only `foodcourt` is filled and every list is empty.
 */
export const PublicMenuSchema = z.strictObject({
  foodcourt: PublicFoodcourtSchema,
  categories: z.array(PublicCategorySchema),
  stalls: z.array(PublicStallSchema),
  stallCategories: z.array(PublicStallCategorySchema),
  foods: z.array(PublicFoodSchema),
  /** «تخفیف امروز»: available foods with a discount active today, in menu order. */
  dealIds: z.array(ObjectIdSchema),
  /** «پرطرفدارها»: up to five available foods, rank order (7-day adds, ties by id). */
  popularIds: z.array(ObjectIdSchema).max(5),
  generatedAt: Instant,
});

export const PublicSearchResponseSchema = z.strictObject({
  stalls: z.array(PublicStallSchema),
  foods: z.array(PublicFoodSchema),
});

export const AdminFoodcourtSchema = FoodcourtInputSchema.extend({
  logoUrl: url.nullable(),
  /** Fixed deployment configuration; read-only. null means not configured. */
  publicMenuUrl: z.string().nullable(),
});

export const AdminStallSchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  intro: z.string(),
  logo: MediaNameSchema.nullable(),
  logoUrl: url.nullable(),
  weeklyHours: WeeklyScheduleSchema,
  manualOverride: ManualOverrideSchema.nullable(),
  isOpen: z.boolean(),
  opensAt: Instant.nullable(),
  sortOrder: z.number().int(),
  visible: z.boolean(),
  isDemo: z.boolean(),
  foodCount: z.number().int(),
  adminUsername: z.string().nullable(),
});

export const AdminCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  icon: CategoryIconSchema,
  sortOrder: z.number().int(),
  foodCount: z.number().int(),
});

export const AdminStallCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  name: z.string(),
  sortOrder: z.number().int(),
  foodCount: z.number().int(),
});

export const AdminFoodSchema = FoodInputSchema.extend({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  imageUrl: url.nullable(),
  finalPrice: PriceSchema,
  discountActive: z.boolean(),
});

export type PublicFoodcourt = z.infer<typeof PublicFoodcourtSchema>;
export type PublicStall = z.infer<typeof PublicStallSchema>;
export type PublicCategory = z.infer<typeof PublicCategorySchema>;
export type PublicStallCategory = z.infer<typeof PublicStallCategorySchema>;
export type PublicFood = z.infer<typeof PublicFoodSchema>;
export type PublicMenu = z.infer<typeof PublicMenuSchema>;
export type PublicSearchResponse = z.infer<typeof PublicSearchResponseSchema>;
export type SearchQuery = z.infer<typeof SearchQuerySchema>;
export type AdminFoodcourt = z.infer<typeof AdminFoodcourtSchema>;
export type AdminStall = z.infer<typeof AdminStallSchema>;
export type AdminCategory = z.infer<typeof AdminCategorySchema>;
export type AdminStallCategory = z.infer<typeof AdminStallCategorySchema>;
export type AdminFood = z.infer<typeof AdminFoodSchema>;
export type FoodInput = z.infer<typeof FoodInputSchema>;
export type TemporaryPasswordResponse = z.infer<typeof TemporaryPasswordResponseSchema>;
