import { z } from 'zod';
import { MAX_DISCOUNT_PERCENT, MAX_PRICE_TOMAN, MIN_DISCOUNT_PERCENT } from './money.js';

// ---------- primitives ----------

export const ObjectIdSchema = z.string().regex(/^[a-f0-9]{24}$/, 'شناسه نامعتبر است.');

/** Stored media file name (random, generated by the server). Never a path. */
export const MediaNameSchema = z.string().regex(/^[a-z0-9][a-z0-9-]{0,80}\.(webp|png|jpg|svg)$/);

const text = (max: number, min = 1) => z.string().trim().min(min).max(max);

export const ROLES = ['stall_admin', 'super_admin'] as const;
export const RoleSchema = z.enum(ROLES);
export type Role = z.infer<typeof RoleSchema>;

export const USERNAME_PATTERN = /^[a-z0-9][a-z0-9._-]{2,31}$/;
export const UsernameSchema = z
  .string()
  .trim()
  .toLowerCase()
  .regex(USERNAME_PATTERN, 'نام کاربری ۳ تا ۳۲ حرف انگلیسی کوچک، عدد، نقطه، خط تیره یا زیرخط است.');

/** Password policy for new passwords: at least 8 characters, at least one letter and one digit. */
export const NewPasswordSchema = z
  .string()
  .min(8, 'رمز باید حداقل ۸ حرف باشد.')
  .max(128, 'رمز طولانی است.')
  .refine((v) => /\p{L}/u.test(v) && /\p{Nd}/u.test(v), 'رمز باید حرف و عدد داشته باشد.');

export const CATEGORY_ICON_KEYS = [
  'pizza',
  'burger',
  'kebab',
  'fried-chicken',
  'steak',
  'sushi',
  'sandwich',
  'dessert',
] as const;
export const CategoryIconSchema = z.enum(CATEGORY_ICON_KEYS);

export const FOOD_TINTS = ['food-tint-1', 'food-tint-2', 'food-tint-3', 'food-tint-4'] as const;
export const FoodTintSchema = z.enum(FOOD_TINTS);

export const SortOrderSchema = z.number().int().min(0).max(10_000);
export const PriceSchema = z.number().int().min(0).max(MAX_PRICE_TOMAN);

/** Tehran local calendar date, ISO formatted (YYYY-MM-DD, Gregorian). The UI converts to/from Jalali. */
export const LocalDateSchema = z.iso.date();

// ---------- schedule ----------

/** "HH:MM" 00:00–23:59. */
export const TimeSchema = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'ساعت نامعتبر است.');
/** Closing time additionally allows "24:00" meaning midnight at the end of the day. */
export const ClosingTimeSchema = z.union([TimeSchema, z.literal('24:00')]);

/**
 * One opening interval per weekday. close < open means the interval runs past midnight
 * into the next day (overnight). open === close is rejected as ambiguous.
 */
export const DayScheduleSchema = z
  .strictObject({ closed: z.boolean(), open: TimeSchema, close: ClosingTimeSchema })
  .refine((d) => d.closed || d.open !== d.close, { message: 'ساعت شروع و پایان یکی است.', path: ['close'] });

/** Exactly seven days; index 0 = Saturday (شنبه) … index 6 = Friday (جمعه), Asia/Tehran local time. */
export const WeeklyScheduleSchema = z.array(DayScheduleSchema).length(7);
export type WeeklySchedule = z.infer<typeof WeeklyScheduleSchema>;

/**
 * Manual open/closed override from the stall panel. `until` is the start of the next scheduled
 * opening interval (computed server-side); null when no future opening exists, in which case the
 * override persists until changed.
 */
export const ManualOverrideSchema = z.strictObject({
  state: z.enum(['open', 'closed']),
  until: z.iso.datetime({ offset: true }).nullable(),
});

// ---------- entities (write inputs) ----------

export const FoodcourtInputSchema = z.strictObject({
  name: text(60),
  logo: MediaNameSchema.nullable(),
  menuOpen: z.boolean(),
  closedMessage: text(200, 0),
});

export const StallInputSchema = z.strictObject({
  name: text(40),
  intro: text(40, 0),
  logo: MediaNameSchema.nullable(),
  weeklyHours: WeeklyScheduleSchema,
  manualOverride: ManualOverrideSchema.nullable(),
  sortOrder: SortOrderSchema,
  visible: z.boolean(),
});

export const GlobalCategoryInputSchema = z.strictObject({
  name: text(30),
  icon: CategoryIconSchema,
  sortOrder: SortOrderSchema,
});

export const StallCategoryInputSchema = z.strictObject({
  name: text(40),
  sortOrder: SortOrderSchema,
});

export const DiscountSchema = z
  .strictObject({
    percent: z.number().int().min(MIN_DISCOUNT_PERCENT).max(MAX_DISCOUNT_PERCENT),
    startDate: LocalDateSchema,
    endDate: LocalDateSchema,
  })
  .refine((d) => d.startDate <= d.endDate, { message: 'تاریخ پایان باید بعد از تاریخ شروع باشد.', path: ['endDate'] });

export const FoodInputSchema = z.strictObject({
  name: text(60),
  description: text(120, 0),
  price: PriceSchema,
  image: MediaNameSchema.nullable(),
  tint: FoodTintSchema,
  categoryId: ObjectIdSchema,
  stallCategoryId: ObjectIdSchema,
  available: z.boolean(),
  discount: DiscountSchema.nullable(),
});

/** Anonymous popularity event: one successful "+" (add or quantity increment) for a food. */
export const PopularityEventSchema = z.strictObject({ foodId: ObjectIdSchema });

// ---------- auth ----------

export const LoginInputSchema = z.strictObject({
  username: z.string().trim().toLowerCase().min(1).max(64),
  password: z.string().min(1).max(128),
});

export const ChangePasswordInputSchema = z
  .strictObject({
    currentPassword: z.string().min(1).max(128),
    newPassword: NewPasswordSchema,
    confirmPassword: z.string(),
  })
  .refine((v) => v.newPassword === v.confirmPassword, { message: 'تکرار رمز یکی نیست.', path: ['confirmPassword'] });

// ---------- responses ----------

export const AccountResponseSchema = z.strictObject({
  id: ObjectIdSchema,
  username: z.string(),
  role: RoleSchema,
  stallId: ObjectIdSchema.nullable(),
});
export type AccountResponse = z.infer<typeof AccountResponseSchema>;

export const SessionResponseSchema = z.strictObject({
  account: AccountResponseSchema,
  csrfToken: z.string(),
});
export type SessionResponse = z.infer<typeof SessionResponseSchema>;

const url = z.string(); // relative media URL such as /api/media/<name>

export const PublicFoodcourtSchema = z.strictObject({
  name: z.string(),
  logoUrl: url.nullable(),
  menuOpen: z.boolean(),
  closedMessage: z.string(),
});

export const PublicStallSchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  intro: z.string(),
  logoUrl: url.nullable(),
  isOpen: z.boolean(),
  /** Start of the next opening, when closed and one exists. */
  opensAt: z.iso.datetime({ offset: true }).nullable(),
  sortOrder: z.number().int(),
});

export const PublicCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  name: z.string(),
  icon: CategoryIconSchema,
  sortOrder: z.number().int(),
});

export const PublicStallCategorySchema = z.strictObject({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  name: z.string(),
  sortOrder: z.number().int(),
});

export const PublicFoodSchema = z.strictObject({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  categoryId: ObjectIdSchema,
  stallCategoryId: ObjectIdSchema,
  name: z.string(),
  description: z.string(),
  price: PriceSchema,
  /** Equals price unless a discount is active today. */
  finalPrice: PriceSchema,
  discountPercent: z.number().int().nullable(),
  imageUrl: url.nullable(),
  tint: FoodTintSchema,
  available: z.boolean(),
});

export const AdminFoodcourtSchema = FoodcourtInputSchema.extend({
  logoUrl: url.nullable(),
  /** Fixed deployment configuration; read-only. null means not configured. */
  publicMenuUrl: z.string().nullable(),
});

export const AdminStallSchema = StallInputSchema.extend({
  id: ObjectIdSchema,
  logoUrl: url.nullable(),
  isDemo: z.boolean(),
});

export const AdminFoodSchema = FoodInputSchema.extend({
  id: ObjectIdSchema,
  stallId: ObjectIdSchema,
  imageUrl: url.nullable(),
});

export type PublicFoodcourt = z.infer<typeof PublicFoodcourtSchema>;
export type PublicStall = z.infer<typeof PublicStallSchema>;
export type PublicCategory = z.infer<typeof PublicCategorySchema>;
export type PublicStallCategory = z.infer<typeof PublicStallCategorySchema>;
export type PublicFood = z.infer<typeof PublicFoodSchema>;
export type AdminFoodcourt = z.infer<typeof AdminFoodcourtSchema>;
export type AdminStall = z.infer<typeof AdminStallSchema>;
export type AdminFood = z.infer<typeof AdminFoodSchema>;
