import { z } from 'zod';

const bool = z.enum(['true', 'false']).transform((v) => v === 'true');

const EnvSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  API_HOST: z.string().default('0.0.0.0'),
  API_PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  MONGODB_URI: z.string().regex(/^mongodb(\+srv)?:\/\//).default('mongodb://127.0.0.1:27017/elay'),
  MEDIA_DIR: z.string().default('./data/media'),
  /** Fixed printed-QR URL. Empty = not configured. Never generated by the app. */
  PUBLIC_MENU_URL: z.union([z.literal(''), z.url()]).default(''),
  /** Secure cookies require HTTPS (localhost is exempt in modern browsers). */
  COOKIE_SECURE: bool.default(true),
  SESSION_TTL_HOURS: z.coerce.number().int().min(1).max(24 * 30).default(12),
  /** Set true only when the API is reachable exclusively through the bundled reverse proxy. */
  TRUST_PROXY: bool.default(false),
  LOGIN_RATE_LIMIT_PER_15M: z.coerce.number().int().min(1).default(10),
});

export type Config = z.infer<typeof EnvSchema>;

export function loadConfig(env: NodeJS.ProcessEnv = process.env): Config {
  const parsed = EnvSchema.safeParse(env);
  if (!parsed.success) {
    // Names only; values may be secrets.
    const fields = parsed.error.issues.map((i) => i.path.join('.')).join(', ');
    throw new Error(`Invalid environment configuration: ${fields}`);
  }
  return parsed.data;
}
